### ISSUE TITLE
PayEx Partpayment and PayEx Factoring/Financing Invoice need TOS text

### ISSUE THREAD

**Issue by PayExBent** [PayEx/PayEx.Magento2#15]
For the payment options "PayEx Partpayment" and "Financing Invoice", PayEx require that the merchant provides Terms of service text for the end user in conjunction with payment. There should be a "read more" or similar text when these options are selected, that links to the necessary information.

See the first information box regarding what is required to mediate to end user:
[Part Payment](http://www.payexpim.com/payment-methods/financing-credit-account/)
[Financing Invoice](http://www.payexpim.com/payment-methods/financing-invoice/)

Current solution shows no information:
![image](https://cloud.githubusercontent.com/assets/16135174/20259188/d4bc4fa2-aa53-11e6-83f6-5c7eb2bf955f.png)

**Comment by aait** [comment]
Dear @PayExBent,

Thanks for your help. We will work on this.

Best,
AAIT

**Comment by aait** [comment]
Impelemented a5c551766757c1b42c304e4bdc713da9ba35e2e7
