### ISSUE TITLE
Payment config not displayed in magento 2.1.3

### ISSUE THREAD

**Issue by bve-9384** [PayEx/PayEx.Magento2#18]
See also http://devdocs.magento.com/guides/v2.1/release-notes/ReleaseNotes2.1.3CE.html#known-issues
_A payment method configuration is not displayed in the Magento Admin if the sort order for the group is not specified or is less than 5_

PayEx config displayed fine after I changed `vendor/payex/magento2-payments/etc/adminhtml/system.xml` and changed `sortOrder="1"` to `sortOrder="6"`.

**Comment by aait** [comment]
Dear @bve-9384,

Thanks for your help. We will test this.

Thanks,
AAIT

**Comment by aait** [comment]
Dear @bve-9384,

We test this on clean 2.1.3 an this issue is not reproduced. Pls make sure you have last version of our extension.

Thanks,
AAIT

**Comment by aait** [comment]
Dear @bve-9384,

It's reproduced in some cases.    

Thanks,
AAIT
