### ISSUE TITLE
Option to disable different billing and delivery address

### ISSUE THREAD

**Issue by arlycreative** [PayEx/PayEx.Magento2#31]
Hi,

We're using your module and wondering if its possible for you to add a option in admin that enables/disables the part that handles different billing and delivery address?

As we only have credit card payment from PayEx and only need delivery address from customers we want to remove that part from checkout in order to make it easy for our customers to order.

**Here's what it looks like today:**

<img width="841" alt="enabled-option" src="https://cloud.githubusercontent.com/assets/22391123/25483130/daa2e17e-2b54-11e7-888f-1b5cc8181219.png">

**And here's how i want it to be:**

<img width="830" alt="disabled-option" src="https://cloud.githubusercontent.com/assets/22391123/25483133/dce23c0a-2b54-11e7-88f3-82c236d92ed4.png">

@aait

**Comment by aait** [comment]
Was implemented in 8d54bf88cab5206b4ba88b58318b90e96390cd75
