### ISSUE TITLE
Option to place order after payment is done

### ISSUE THREAD

**Issue by arlycreative** [PayEx/PayEx.Magento2#32]
Today your extension creates the order before the payment is done. What we want is to choose that rather than before payment, the order is placed after payment is done and succeeded.

The problem we're having is that all orders no matter if the customer pays or not gets placed and are visible in backend.

Is it possible to add an option so that we can choose if order should be created before or after payment is done? @aait

**Comment by olegisk** [comment]
@arlycreative It's impossible because payex use "redirect" method for payments processing. It's mean that order should placed in store before redirect and marked as "paid" (or another status) after payment.
