### ISSUE TITLE
unable to find payex method after installing

### ISSUE THREAD

**Issue by nafisakanwal** [PayEx/PayEx.Magento2#37]
I have added this extension into my magento-root/app/code folder with name of 'payex' , after success full upgrade command i am still unable to find any payex payment method at my admin side.
P.s i am using it in pakistan , i hope thats not the problem?

Can any one help/guide me 
Thanks in advance

**Comment by asbjornu** [comment]
@nafisakanwal: Is there a reason why you're not installing the [plugin from the Magento Marketplace](https://marketplace.magento.com/payex-magento2-payments.html)?

**Comment by aait** [comment]
It should be under store-> configuration->sales->payment methods , like all Payment Methods
![image](https://cloud.githubusercontent.com/assets/6286270/26051853/c66b352c-3963-11e7-8dc7-602680f15e9c.png)

**Comment by nafisakanwal** [comment]
@asbjornu 
I am trying to install it from magento marketplace but now i am stucked in Readiness Check >

Check Component Dependency

We found conflicting component dependencies. Hide detail

Command "update" failed: Loading composer repositories with package information



[Composer\Downloader\TransportException]
The "https://repo.magento.com/packages.json" file could not be downloaded: php_network_getaddresses: getaddrinfo failed: Name or service not known
failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known



update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [packages1] ... [packagesN]


For additional assistance, see component dependency help .

**Comment by aait** [comment]
@nafisakanwal I think problem in firewall rules on your server: firewall block outcomming connections
