### ISSUE TITLE
Transaction status in order view page. user-friendly text instead code 

### ISSUE THREAD

**Issue by vmalyk** [PayEx/PayEx.Magento2#39]
In payment information Transaction status is shows as some code: http://prntscr.com/fbh8wv. I found callback statuses http://www.payexpim.com/quick-guide/9-transaction-callback/, but I cannot find that code equals text status. Is possible to show user-friendly status or can provide reference code-value for transaction status?

**Comment by bve-9384** [comment]
I found the following comment in the callback controller:
/* Transaction statuses: 0=Sale, 1=Initialize, 2=Credit, 3=Authorize, 4=Cancel, 5=Failure, 6=Capture */

Controller\Transaction\Index.php
