### ISSUE TITLE
Incorrect PayEx\Px version by tag

### ISSUE THREAD

**Issue by unicoder88** [PayEx/PayEx.Magento2#4]
`PayEx\Payments\Helper\Data::getPx() `references constant `\PayEx\Px::VERSION`,
but it doesn't exist in code by composer required tag `"payex/php-api": "~1.0.1"` since it was added in next commit after tag 1.0.1.
The only solution currently is to require `"payex/php-api": "dev-master"`, which is not clean.
So new tag needs to be created and referenced.

**Comment by aait** [comment]
Fixed. Tag has been updated.
