### ISSUE TITLE
Feedback on the Callback controller

### ISSUE THREAD

**Issue by bve-9384** [PayEx/PayEx.Magento2#40]
Some feedback after testing the callback controller (Controller\Transaction\Index.php):

1) Logical error on line 143: "if (!$transaction)" should be replaced with "if ($transaction)". Processing should end if the transaction already exists, not the other way around.

2) Line 145 and 146: The controller should not respond with a failure if the transaction already exists in Magento. Should return OK instead

3) Line 205: The assignment messes up the result variable, should not replace it. Maybe change to the following:
                $px_result = $this->payexHelper->getPx()->Complete($params);
                if ($px_result['errorCodeSimple'] !== 'OK') {
                    $logger->err('Failed to complete payment', $px_result);

4) The controller response does not comply to the Payex implementation guide (here: http://www.payexpim.com/quick-guide/9-transaction-callback/)
- The response code/header should always be HTTP 200 OK while the controller often responds with HTTP 500
- The body should be set to "FAILED" not "FAILURE" in case the request cannot be processed

I wonder if this piece of code was ever properly tested.

**Comment by aait** [comment]
Hi @bve-9384 This issue can be applied for another payex modules: Magento 1, WooCommerce, PrestaShop and OpenCart
