### ISSUE TITLE
Rounding errors when converting from float to integer

### ISSUE THREAD

**Issue by bve-9384** [PayEx/PayEx.Magento2#43]
The following lines of code do not round correctly. From all Model\Method classes that call PxOrder.AddSingleOrderLine2

```
                    'amount' => (int)(100 * $item['price_with_tax']), //must include tax
                    'vatPrice' => (int)(100 * $item['tax_price']),

```
My fix:

```
                    'amount' => (int)(100 * $item['price_with_tax'] + 0.5), //must include tax
                    'vatPrice' => (int)(100 * $item['tax_price'] + 0.5),

```

In practice this problem mainly impacts VAT amounts ("vatPrice"). The PayEx service seems to accept VAT amounts with rounding errors for most payment methods but not Swish

**Comment by olegisk** [comment]
Fixed https://github.com/PayEx/PayEx.Magento2/commit/434c941382da8b8c6f8e50a5a11bf1db0aa7c47a
