### ISSUE TITLE
Swish improvement: Default to customer telephone number if mobile

### ISSUE THREAD

**Issue by bve-9384** [PayEx/PayEx.Magento2#49]
80% of our Swedish customers enter a mobile phone number as the billing address phone number but still need to enter a mobile phone number at PayEx when paying with Swish.

I suggest that the plugin sends any existing mobile number when calling "PxOrder.Initialize8", using the additional value "MSISDN". This way, 80% of our customers do not have to enter their mobile number twice.

Proposed change to Model/Method/Swish.php (initialize() function, only works for Swedish phone numbers - needs filter on country):

```
        // Get Additional Values
        $additional = '';

        // Also send mobile number if available
        $telephone = str_replace([' ', '-'], '', $order->getBillingAddress()->getTelephone());
        $mobile_prefixes = array('070', '072', '073', '076', '079');
        if (strlen($telephone) == 10 && in_array(substr($telephone, 0, 3), $mobile_prefixes)) {
            $additional = 'MSISDN=46' . substr($telephone, 1);
        }

        // Responsive Skinning

```

**Comment by olegisk** [comment]
Should be implemented it for another payment modules?

**Comment by olegisk** [comment]
https://github.com/PayEx/PayEx.Magento2/commit/14ebf88bdbfab21beac22d3af32d89608b8e10bd
