### ISSUE TITLE
Class 'PayEx\Px' not found error in C:\xampp\htdocs\project_name\app\code\PayEx\Payments\Helper\Data.php:176

### ISSUE THREAD

**Issue by Kuntal32** [PayEx/PayEx.Magento2#50]
Hello
   I have added this extension into my magento 2 project. Admin panle is working properly. But in front end I'm getting error 
"Class 'PayEx\Px' not found error in C:\xampp\htdocs\project_name\app\code\PayEx\Payments\Helper\Data.php:176"  in  checkout/cart and checkout pages. 

Thank you.

**Comment by bve-9384** [comment]
See https://github.com/PayEx/PayEx.Ecommerce.Php

Did you try to install from GitHub directly?

**Comment by Kuntal32** [comment]
No. I have installed it from magento marcketplace. 

Thank you.

**Comment by olegisk** [comment]
Hi @Kuntal32 
Please install missed libraries using composer:
composer require payex/php-api
composer require aait/php-name-parser

Please note that you are should install composer on your Windows. See https://getcomposer.org/doc/00-intro.md
