### ISSUE TITLE
Exception #0 (SoapFault): SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://test-external.payex.com/pxorder/pxorder.asmx?WSDL' : failed to load external entity "https://test-external.payex.com/pxorder/pxorder.asmx?WSDL"

### ISSUE THREAD

**Issue by Kuntal32** [PayEx/PayEx.Magento2#55]
Hello,
     I'm getting following error during payex payment in magento 2. 
"1 exception(s):
Exception #0 (SoapFault): SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://test-external.payex.com/pxorder/pxorder.asmx?WSDL' : failed to load external entity "https://test-external.payex.com/pxorder/pxorder.asmx?WSDL""

Also I have attached screenshot regarding this issue. Please Help.
![error](https://user-images.githubusercontent.com/17197095/32659130-2c117adc-c643-11e7-81e4-ca700d823e0f.jpg)

**Comment by bve-9384** [comment]
Payex just changed their test URLs
https://github.com/PayEx/PayEx.Magento2/issues/54

**Comment by olegisk** [comment]
Hi @Kuntal32. You are should upgrade payex/php-api library via composer: composer update payex/php-api

**Comment by Kuntal32** [comment]
Thank you.
