### ISSUE TITLE
 [ReflectionException]   Class PayEx\Px does not exist error on compiling

### ISSUE THREAD

**Issue by petnutz** [PayEx/PayEx.Magento2#56]
[ReflectionException]   Class PayEx\Px does not exist error on compiling

**Comment by olegisk** [comment]
Try to install using composer:
composer require payex/php-api
and let me know.

**Comment by olegisk** [comment]
https://github.com/PayEx/PayEx.Magento2/commit/f0106223ee5b29d2c3b5f58cdf0e219e15a8d4d4
https://github.com/PayEx/PayEx.Magento2/commit/b5ead205456514e76bf513ab60355615a4b6ea12
https://github.com/PayEx/PayEx.Magento2/commit/f465f7855f04be2cabb24f48ee1e660c8abead55
