### ISSUE TITLE
Magento 2.2 support

### ISSUE THREAD

**Issue by asbjornu** [PayEx/PayEx.Magento2#57]
[TorL asks on Magento Marketplace](https://marketplace.magento.com/catalog/product/view/id/3848/s/payex-magento2-payments/#bv_questions): 

> When will you support Magento 2.2?

Do we have an answer for him?

**Comment by olegisk** [comment]
Payex module is working with Magento 2.2

**Comment by asbjornu** [comment]
TorL writes:

> It only says 2.0 and 2.1 in the compatibility list. I don't wish to install it before I have official confirmation that it works on 2.2.

**Comment by olegisk** [comment]
Compatibility list was updated on magento marketplace (v1.0.13). But status still "Ready for Marketing Review". Therefore, the update is still not available.

**Comment by asbjornu** [comment]
Ok.
