### ISSUE TITLE
Update ToS for PayEx Delbetala

### ISSUE THREAD

**Issue by DavidPayEx** [PayEx/PayEx.Magento2#59]
Currently there is an "error" in the ToS for delbetala service:
https://github.com/PayEx/PayEx.Magento2/blob/55205f689ab6f4106f04068efce705b958305324/view/frontend/templates/checkout/terms_of_service.phtml

At the end of the terms there is a text that says [Kund anger den faktureringsavgift kund tillämpar] which is not easy to change if you havent used Wordpress/coding before.

Is it possible to implement to that customer can change this value?

**Comment by aait** [comment]
Make all of the ToS content editable in backend,
