### ISSUE TITLE
full amount is sent to payex even if customer has coupon code applied

### ISSUE THREAD

**Issue by mildasilei** [PayEx/PayEx.Magento2#68]
If customer applied coupon code in checkout and get a discount in Payex he/she still have to pay full amount, e.g.:
- a customer wants to buy shoes which cost 100,-
-  a customer apply a coupon code which gave him 50% discount
- for customer grand total is 50,-
- in payex customer still have to pay 100,-

We check your code and we see the issue is because you are calculating items price but coupon codes and shopping car discounts Magento is calculating base on subtotal and not each product individually.

**Comment by olegisk** [comment]
Fixed https://github.com/PayEx/PayEx.Magento2/commit/531b6186af45e964950901dc962970500ccb2c17
