### ISSUE TITLE
Can't install with Magento 2.0.9

### ISSUE THREAD

**Issue by andersro93** [PayEx/PayEx.Magento2#8]
Trying to:
Install the module on Magento 2.0.9 using composer from a company's own git repo. Because we need to add translation files to the module for various languages.

Expected:
The module to be installed

Got:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for payex/magento2-payments 1.0.2 -> satisfiable by payex/magento2-payments[1.0.2].
    - Conclusion: remove magento/framework 100.0.11
    - magento/product-community-edition 2.0.9 requires magento/framework 100.0.11 -> satisfiable by magento/framework[100.0.11].
    - magento/product-community-edition 2.0.9 requires magento/framework 100.0.11 -> satisfiable by magento/framework[100.0.11].
    - Conclusion: don't install magento/framework 100.0.11
    - Installation request for magento/product-community-edition ~2.0.9 -> satisfiable by magento/product-community-edition[2.0.9].

**Comment by aait** [comment]
Fixed #3ddbd76f938447d5b5f56be4f9a60e67ebbeb58f
Please try to install again using composer
